phase: prototype

prototype:
    downloaded_data: /app/data/dl_data.json
    processed_data: /app/data/dummy_data.json

tags:
    - "Python"
    - "JavaScript"
    - "Ruby"
    - "Rails"
    - "PHP"
    - "AWS"
    - "初心者"
    - "Git"
    - "GitHub"
    - "Docker"
    - "Linux"
    - "Java"
    - "HTML"
    - "CSS"
    - "Node.js"
    - "iOS"
    - "Vue.js"
    - "Android"
    - "React"
    - "機械学習"
